#!/bin/bash
set -e

function rand() {
	[ "$2" == "0" ] && CHAR="[:alnum:]" || CHAR="[:graph:]"
	cat /dev/urandom | tr -cd "$CHAR" | head -c ${1:-48}
	echo
}

tar -C /var/www -xzf /tmp/phpMyAdmin-${PHPMYADMIN_VERSION}-english.tar.gz
rm -rf /var/www/html
mv /var/www/phpMyAdmin-${PHPMYADMIN_VERSION}-english /var/www/html

# configure phpMyAdmin
cat > /var/www/html/config.inc.php <<EOF
<?php
/* Servers configuration */
\$i = 0;
\$i++;
\$cfg['Servers'][\$i]['host'] = 'mysql';
\$cfg['Servers'][\$i]['port'] = '';
\$cfg['Servers'][\$i]['socket'] = '';
\$cfg['Servers'][\$i]['connect_type'] = 'tcp';
\$cfg['Servers'][\$i]['extension'] = 'mysqli';
\$cfg['Servers'][\$i]['auth_type'] = 'cookie';
\$cfg['Servers'][\$i]['user'] = '';
\$cfg['Servers'][\$i]['password'] = '';

/* End of servers configuration */

\$cfg['blowfish_secret'] = '$(rand 40 0)';
\$cfg['UploadDir'] = '';
\$cfg['SaveDir'] = '';
\$cfg['NavigationTreeTableLevel'] = 3;
\$cfg['MaxNavigationItems'] = 200;
\$cfg['RememberSorting'] = false;
\$cfg['VersionCheck'] = false;
\$cfg['PmaNoRelation_DisableWarning'] = true;
\$cfg['SuhosinDisableWarning'] = true;
\$cfg['Export']['htmlword_columns'] = true;
\$cfg['Export']['compression'] = 'gzip';
\$cfg['Export']['charset'] = 'utf-8';
\$cfg['Export']['file_template_table'] = '@SERVER@-@DATABASE@-@TABLE@-%Y%m%dT%H%M%S%Z';
\$cfg['Export']['file_template_database'] = '@SERVER@-@DATABASE@-%Y%m%dT%H%M%S%Z';
\$cfg['Export']['file_template_server'] = '@SERVER@-%Y%m%dT%H%M%S%Z';
EOF
